name: Deploy

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: stable
        override: true
    - name: Build
      run: cargo build
    - name: Extract version from tag
      id: get_version
      run: echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"
    - name: Set and publish workspace crates
      run: |
        cargo install cargo-workspaces
        ls
        git status
        git branch
        cargo workspaces version custom ${{ steps.get_version.outputs.version }} \
          --exact --yes --no-individual-tags \
          -m "Commit new release ${{ steps.get_version.outputs.version }}"
        cargo workspaces publish --yes --no-verify
