name: Test all targets

on: [push, pull_request]

jobs:
  quick-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1.0.1
      with:
        toolchain: stable
        target: ${{ matrix.TARGET }}
        override: true
    - name: Check Type
      run: cargo fmt -- --check
    - name: Run internal tests
      run: cargo test --verbose --features all-dialects -- --nocapture
    - name: Build mavlink-dump
      run: cargo build --verbose --bin mavlink-dump --features ardupilotmega

  build:
    needs: quick-tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
          TARGET: x86_64-apple-darwin
          FEATURES: --features all-dialects

        - os: ubuntu-latest
          TARGET: arm-unknown-linux-musleabihf
          FLAGS: --features ardupilotmega

        - os: ubuntu-latest
          TARGET: armv7-unknown-linux-musleabihf
          FLAGS: --features ardupilotmega

        - os: ubuntu-latest
          TARGET: x86_64-unknown-linux-musl
          FLAGS: --features all-dialects

        - os: ubuntu-latest
          TARGET: x86_64-unknown-linux-musl
          FLAGS: --features all-dialects,emit-extensions

        - os: ubuntu-latest
          TARGET: thumbv7m-none-eabi
          FLAGS: --no-default-features --features embedded

        - os: windows-latest
          TARGET: x86_64-pc-windows-msvc
          FLAGS: --features all-dialects

    steps:
    - name: Building ${{ matrix.TARGET }}
      run: echo "${{ matrix.TARGET }}"
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1.0.1
      with:
        toolchain: stable
        target: ${{ matrix.TARGET }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --verbose --release --target=${{ matrix.TARGET }} ${{ matrix.FLAGS }}

  test-embedded-size:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1.0.1
      with:
        toolchain: nightly
        target: thumbv7em-none-eabihf
        override: true
    - name: Build
      run: cargo +nightly build --target thumbv7em-none-eabihf --manifest-path examples/embedded/Cargo.toml --out-dir $PWD --release -Z unstable-options
    - name: Get binary size
      id: get_binary_size
      run: |
        find . | grep mavlink-embedded
        ls ./mavlink-embedded
        ls ./examples/embedded/target/thumbv7em-none-eabihf/release/mavlink-embedded
        size -G -d mavlink-embedded
        size -G -d ./examples/embedded/target/thumbv7em-none-eabihf/release/mavlink-embedded
        size -G -d mavlink-embedded &> output.txt
        cat output.txt
        # Sanitize string for github env variable
        export OUTPUT="$(cat output.txt)"
        BODY_SIZE="${OUTPUT//'%'/'%25'}"
        BODY_SIZE="${OUTPUT//$'\n'/'%0A'}"
        BODY_SIZE="${OUTPUT//$'\r'/'%0D'}"
        echo "::set-output name=body_size::${BODY_SIZE}"
    - name: Comment PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: 'Size of the binary:<br>${{ steps.get_binary_size.outputs.body_size }}'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/[0-9]+\.[0-9]+\.[0-9]+')
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1.0.1
      with:
        toolchain: stable
        override: true
    - uses: katyo/publish-crates@v1
      with:
        registry-token: ${{ secrets.CARGO }}
